### ISSUE TITLE
Copiar contenido de web de 2022 a 2023 (este repo)

### ISSUE THREAD

**Issue by dukebody** [HacktoberfestES/hacktoberfestES2023#1]
Tenemos la web del 2022 aquí: https://github.com/HacktoberfestES/hacktoberfestES2022-web

Podemos copiar todos los archivos sin más.

**Comment by aalmiramolla** [comment]
Me pongo con ello!

**Comment by aalmiramolla** [comment]
Copiado 1:1 en este commit https://github.com/HacktoberfestES/hacktoberfestES2023/commit/66e12bbe04647522291116f0d63c2ad32a019f50
