### ISSUE TITLE
Publicar evento PyData Madrid

### ISSUE THREAD

**Issue by dukebody** [HacktoberfestES/hacktoberfestES2023#10]
Hay interés. Contacto: @astrojuanlu.

Si finalmente sale, publicar la información del evento, y sus proyectos si los hubiere, en la web.

**Comment by dukebody** [comment]
@astrojuanlu podrías hacer un PR como https://github.com/HacktoberfestES/hacktoberfestES2023/pull/23 añadiendo vuestros eventos?

**Comment by astrojuanlu** [comment]
Sí, cuando lo tengamos cerrado

**Comment by astrojuanlu** [comment]
En cuanto lo tengamos en Meetup lo publicamos 😉

**Comment by dukebody** [comment]
@astrojuanlu están ya publicados?

**Comment by astrojuanlu** [comment]
Hemos tenido problemas con la sede pero hace apenas unos minutos hemos encontrado alternativa https://www.meetup.com/pydata-madrid/events/296832658/
