### ISSUE TITLE
Publicar evento de La Coruña

### ISSUE THREAD

**Issue by dukebody** [HacktoberfestES/hacktoberfestES2023#11]
Hay interés. Contacto: @yisus82

Si finalmente sale, publicar la información del evento, y sus proyectos si los hubiere, en la web.

**Comment by dukebody** [comment]
@yisus82 nos podrías hacer un resumen de cómo va la preparación del Hacktoberfest en L Coruña?

**Comment by yisus82** [comment]
Esta semana subiremos una PR con la info del evento

**Comment by soulcodex** [comment]
@dukebody mi esposa @ansm8 esta participando con vosotros en el [rediseño de la web](https://github.com/HacktoberfestES/hacktoberfestES2023/issues/3) nosotros la semana que viene subiremos la PR con el evento de A Coruña para el Hacktoberfest :rocket: lo comento porque asi tambien podriamos ver como queda la UI con este evento :wink:

**Comment by dukebody** [comment]
Solucionado mediante https://github.com/HacktoberfestES/hacktoberfestES2023/pull/23.
