### ISSUE TITLE
Publicar web antigua en 2022.hacktoberfestes.dev

### ISSUE THREAD

**Issue by dukebody** [HacktoberfestES/hacktoberfestES2023#13]
Estaría guay dejar las webs de ediciones antiguas publicadas, al igual que pasa con otros eventos.

Una vez tengamos https://github.com/HacktoberfestES/hacktoberfestES2023/issues/12 o antes si es posible, publicar la versión antigua en 2022.hacktoberfestes.dev. Se puede cambiar el sistema de deployment o dejarlo igual.

**Comment by cprada87** [comment]
Bloqueada por #12

**Comment by aalmiramolla** [comment]
Este issue se debe de mover al repositorio de la web del 2022
