### ISSUE TITLE
Recuperar el Discord?

### ISSUE THREAD

**Issue by aalmiramolla** [HacktoberfestES/hacktoberfestES2023#15]
En ediciones pasadas nos organizábamos por Discord. ¿Vamos a continuar con esta estrategia?

**Comment by dukebody** [comment]
¡Me parece buena idea! Los grupos locales pueden comunicarse como quieran, pero puede estar guay tener un espacio de chat listo para gente que quiera colaborar de forma remota, y para los grupos locales también sirve tener ya algo configurado en vez de tener que crear algo de cero.

Ya he entrado de nuevo al Discord después de un año. Debemos regenerar el enlace de invitación de la web, que está caducado.

Probablemente también queramos reajustar la estructura de canales. 

¿Qué opinas @aalmiramolla ? ¿Te puedes hacer cargo tú de configurar el server de Discord?

**Comment by aalmiramolla** [comment]
Sí, me hago cargo yo de configurar el server de Discord como del issue #16
