### ISSUE TITLE
Actualizar enlace Discord en página web

### ISSUE THREAD

**Issue by dukebody** [HacktoberfestES/hacktoberfestES2023#16]
El enlace que hay al server de Discord en la web ya no funciona.

https://hacktoberfestes.dev/#registrate

Hay que generar uno nuevo y cambiar el enlace en la web nueva.

**Comment by aalmiramolla** [comment]
Realizado en el commit https://github.com/HacktoberfestES/hacktoberfestES2023/commit/f51ea8270c60aa139e476e6dc1e1dfe712ec94f3
