### ISSUE TITLE
Borrar logo Python Chile de colaboradores?

### ISSUE THREAD

**Issue by aalmiramolla** [HacktoberfestES/hacktoberfestES2023#18]
En la web aparece Python Chile de colaborador, ya que en ediciones anteriores colaboraba para realizar este evento.

Puesto que este año no participan, ¿debemos borrar el logo?

@dukebody

**Comment by dukebody** [comment]
@cmaureir ¿qué opinas tú? ¿Crees que Python Chile colaborará con eventos locales, coordinando, o proyectos?

Si no, borramos el logo sin problema.

**Comment by cprada87** [comment]
yo también estoy cogiendo issues, lo mismo podríamos poner también el de python_granada

**Comment by cprada87** [comment]
@dukebody ahora que estamos actualizando el diseño de la 2023, qué hacemos con esta question?

**Comment by dukebody** [comment]
Eliminemos de momento a Python Chile ya que de momento no participa. Si
participa en el futuro se añade y ya está, será rápido.

**Comment by aalmiramolla** [comment]
Solucionado commit https://github.com/HacktoberfestES/hacktoberfestES2023/commit/2a25233f57461ea0e9755b28d34ad728cd52ef85
