### ISSUE TITLE
Actualizar fechas evento a 2023

### ISSUE THREAD

**Issue by dukebody** [HacktoberfestES/hacktoberfestES2023#2]
Una vez copiada la web antigua con https://github.com/HacktoberfestES/hacktoberfestES2023/issues/1, cambiar todas las fechas de la página a 2023.

**Comment by aalmiramolla** [comment]
Realizado en el commit https://github.com/HacktoberfestES/hacktoberfestES2023/commit/dcfd4e8a71c3fad9ebc5a7d6ba8b966cfe0c464c
