### ISSUE TITLE
Añadir enlace a web para proponer nuevos eventos o actividades

### ISSUE THREAD

**Issue by dukebody** [HacktoberfestES/hacktoberfestES2023#21]
Ahora mismo mostramos los eventos de la agenda, pero a diferencia de los proyectos, no hay un botón para proponer nueva actividad.

Añadir uno, con enlace a https://github.com/HacktoberfestES/hacktoberfestES2023/issues/new?assignees=&labels=actividad&projects=&template=actividad.yaml&title=%5BACTIVIDAD%5D+%3Cnombre+de+la+actividad%3E.

**Comment by cprada87** [comment]
cómo tienes en mente que sea el botón para la nueva actividad?

**Comment by dukebody** [comment]
¿Algo así?

![image](https://github.com/HacktoberfestES/hacktoberfestES2023/assets/41953/fc5d4270-1836-40ba-82b7-7c276fb62f32)

**Comment by cprada87** [comment]
bloqueada por #3

**Comment by aalmiramolla** [comment]
Solucionado en commit https://github.com/HacktoberfestES/hacktoberfestES2023/commit/358accc36bfefc51590ffd3682209d64b61543d8
