### ISSUE TITLE
Actualizar diseño de web al estilo de Hacktoberfest 2023

### ISSUE THREAD

**Issue by dukebody** [HacktoberfestES/hacktoberfestES2023#3]
Cada año cambia el estilo del Hacktoberfest oficial.

Habría que cambiar logo y colores de nuestra web cuando DigitalOcean publique la nueva versión (sobre Septiembre). Bloqueada hasta entonces.

**Comment by aalmiramolla** [comment]
Se debe de desbloquear este issue, ya que ya han salido los guidelines: https://do.co/hacktoberbrand

**Comment by ansm8** [comment]
Hola 👋🏽 mi nombre es Andrea Sosa

Actualmente me encuentro formándome como diseñadora UX/UI y además tengo conocimientos de **HTML**, **CSS**, y **JavaScript**. Me pregunto si les interesaría que participara en actualizar el diseño web de este año para el **Hacktoberfest 2023** (diseño en figma e implementación).

En caso de que sea bienvenida mi participación en el rediseño, me gustaría aclarar algunas dudas que tengo respecto al diseño.

Saludos y gracias! 😊

@dukebody @aalmiramolla @cprada87 @cmaureir

**Comment by cprada87** [comment]
Hola @ansm8!

Nos alegra que quieras formar parte! Tenemos un grupo de telegram dónde gestionamos más a fondo el tema de las issues, si tienes usuario allí, búscame por @dev_morphheus y nos cuentas

**Comment by dukebody** [comment]
@ansm8 he mirado tu diseño de Figma que nos pasaste por Telegram y lo veo muy guay!  Currazo hacer un Figma.

Si quieres, revisa [la guía de estilo oficial](https://www.figma.com/proto/DqMlNjNLk5ISe9qn3Prb0e/Hacktoberfest-2023---Brand-Guidelines?page-id=0%3A1&node-id=11702-1806&scaling=contain) por si quieres adaptar colores, texto o lo que sea. Pero vamos, con lo que has hecho ya está guay. Por mi parte, adelante.

¿Necesitas ayuda para ponerte con la implementación?

**Comment by aalmiramolla** [comment]
Cerrado con el PR #22
