### ISSUE TITLE
[PROYECTO] python-api-consumer - python

### ISSUE THREAD

**Issue by EnriqueSoria** [HacktoberfestES/hacktoberfestES2023#33]
### Nombre

python-api-consumer

### Enlace a Github

https://github.com/EnriqueSoria/python-api-consumer

### Tecnologías empleadas

python

### Descripción corta

Framework para crear clientes basados en clases para APIs HTTP.

### Prepara tu proyecto para el HacktoberfestES

- [X] El proyecto está marcado con la etiqueta `hacktoberfest`.
- [ ] El proyecto tiene un README indicando cómo configurarlo para desarrollar en él.
- [X] El proyecto tiene creadas issues con información clara sobre las mejoras a implementar.

**Comment by dukebody** [comment]
Hola @EnriqueSoria . 

Gracias por proponer el proyecto. ¿Podrías añadirlo tú mismo a la web creando un PR como https://github.com/HacktoberfestES/hacktoberfestES2023/pull/29 ?

**Comment by EnriqueSoria** [comment]
> Hola @EnriqueSoria .
> 
> Gracias por proponer el proyecto. ¿Podrías añadirlo tú mismo a la web creando un PR como #29 ?

Claro! pensaba que estaría automatizado

**Comment by EnriqueSoria** [comment]
Hecho! #36

**Comment by dukebody** [comment]
¡Gracias!
