### ISSUE TITLE
Publicar evento Granada

### ISSUE THREAD

**Issue by dukebody** [HacktoberfestES/hacktoberfestES2023#7]
La Oficina de Software Libre de la Universidad de Granada está pensando en organizar un evento. El contacto allí es @fergunet.

Si finalmente sale, publicar la información del evento, y sus proyectos si los hubiere, en la web.

**Comment by dukebody** [comment]
@cprada87 ¿te puedes encargar tú de esto, ya que vives por Granada y conoces a @fergunet?

**Comment by fergunet** [comment]
Sí, estamos ya en contacto por telegram. Tenía pendiente llamarte a tí por teléfono para que me contaras un poco la movida, pero estoy a full y lo tenía pendiente. Si @cprada87 ya está al tanto genial, hablo con él :)

**Comment by dukebody** [comment]
Perfecto. Puedes llamarme también siempre que quieras, encantado de hablar contigo para ver cómo va todo y tal :)

**Comment by fergunet** [comment]
Buenas! Tras hablar con @cprada87 ya tenemos medio montado el evento. Echadle un vistazo a ver si está todo OK en https://osl.ugr.es/2023/09/25/charlas-esenciales-para-el-hacktoberfest-2023/ y si queréis, podéis ponerlo en la web.

Un saludo!

**Comment by cprada87** [comment]
Perfecto @fergunet como siempre!!

**Comment by dukebody** [comment]
Está publicado el evento? No lo veo en la web

**Comment by cprada87** [comment]
Cierto. Esta tarde lo miro

**Comment by dukebody** [comment]
@fergunet @cprada87 podríais hacer un PR como https://github.com/HacktoberfestES/hacktoberfestES2023/pull/23 añadiendo vuestros eventos?

**Comment by cprada87** [comment]
estoy yo con ello

**Comment by cprada87** [comment]
resuelto en https://github.com/HacktoberfestES/hacktoberfestES2023/pull/29
